---
- name: Create a database in MariaDB
  hosts: webserver
  become: yes
  tasks:
    - name: Create a new database
      mysql_db:
        name: my_database
        state: present
        login_user: root
        login_password: asd123.

